version: '3.8'

services:
  user-management-frontend:
    build:
      context: ./user-management-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - user-management-api

  user-management-api:
    build:
      context: ./user-management-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql-standalone:3306/users
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mysql-standalone

  mysql-standalone:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-connector-java:/usr/share/java/mysql-connector-java

volumes:
  mysql_data:
